127.0.0.1 - http://127.0.0.1:8080/logout - - [2023-04-23 16:09:55,249] - app:auth:63 - INFO - User logged out: id=1; name=Timur
127.0.0.1 - http://127.0.0.1:8080/password_recovery - - [2023-04-23 16:09:59,763] - app:auth:89 - INFO - The recovery email has been sent to zvpopeda123@yandex.ru
127.0.0.1 - http://127.0.0.1:8080/reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNjgyMjU1OTk5LjM4MTUxMTR9.bUZQN4ib9N18AYPyxIrME7tQ3ev7v0pZRwMU6UWxAv8 - - [2023-04-23 16:10:13,484] - app:auth:126 - INFO - User has recovered the password: id=4; name=popeda123
127.0.0.1 - http://127.0.0.1:8080/login - - [2023-04-23 16:10:42,731] - app:auth:25 - INFO - User has logged in: id=4; name=popeda123
127.0.0.1 - http://127.0.0.1:8080/posts/5 - - [2023-04-23 16:10:52,005] - app:views:83 - INFO - User attached file: user_id=4, username=popeda123; filename=static/img/user/content/5/22/1.jpg
127.0.0.1 - http://127.0.0.1:8080/posts/5 - - [2023-04-23 16:10:52,013] - app:views:96 - INFO - User has commented post: user_id=4, username=popeda123; post_id=5; comment_id=22
127.0.0.1 - http://127.0.0.1:8080/delete-comment/22 - - [2023-04-23 16:10:58,909] - app:views:125 - INFO - User has deleted comment: user_id=4, username=popeda123; post_id=5; comment_id=22
127.0.0.1 - http://127.0.0.1:8080/posts/5 - - [2023-04-23 16:11:14,509] - app:views:83 - INFO - User attached file: user_id=4, username=popeda123; filename=static/img/user/content/5/22/1.jpg
127.0.0.1 - http://127.0.0.1:8080/posts/5 - - [2023-04-23 16:11:14,518] - app:views:96 - INFO - User has commented post: user_id=4, username=popeda123; post_id=5; comment_id=22
127.0.0.1 - http://127.0.0.1:8080/delete-comment/22 - - [2023-04-23 16:11:21,739] - app:views:125 - INFO - User has deleted comment: user_id=4, username=popeda123; post_id=5; comment_id=22
127.0.0.1 - http://127.0.0.1:8080/change_avatar - - [2023-04-23 16:12:27,930] - app:views:235 - INFO - User changed avatar: user_id=4, username=popeda123
127.0.0.1 - http://127.0.0.1:8080/edit_about - - [2023-04-23 16:12:36,330] - app:views:283 - INFO - User changed 'about': user_id=4, username=popeda123
127.0.0.1 - http://127.0.0.1:8080/change_password - - [2023-04-23 16:12:48,540] - app:views:217 - INFO - User changed password: user_id=4, username=popeda123
127.0.0.1 - http://127.0.0.1:8080/logout - - [2023-04-23 16:13:00,448] - app:auth:63 - INFO - User logged out: id=4; name=popeda123
127.0.0.1 - http://127.0.0.1:8080/sign-up - - [2023-04-23 16:13:08,170] - app:auth:53 - INFO - New user has registered: id=5; name=ppzoveda
127.0.0.1 - http://127.0.0.1:8080/login - - [2023-04-23 16:13:11,255] - app:auth:25 - INFO - User has logged in: id=5; name=ppzoveda
127.0.0.1 - http://127.0.0.1:8080/posts/5 - - [2023-04-23 16:15:51,391] - app:views:83 - INFO - User attached file: user_id=5, username=ppzoveda; filename=static/img/user/content/5/22/1.jpg
127.0.0.1 - http://127.0.0.1:8080/posts/5 - - [2023-04-23 16:15:51,417] - app:views:96 - INFO - User has commented post: user_id=5, username=ppzoveda; post_id=5; comment_id=22
127.0.0.1 - http://127.0.0.1:8080/logout - - [2023-04-23 16:15:54,097] - app:auth:63 - INFO - User logged out: id=5; name=ppzoveda
127.0.0.1 - http://127.0.0.1:8080/login - - [2023-04-23 16:16:01,431] - app:auth:25 - INFO - User has logged in: id=1; name=Timur
127.0.0.1 - http://127.0.0.1:8080/delete-comment/22 - - [2023-04-23 16:16:14,025] - app:views:125 - INFO - User has deleted comment: user_id=1, username=Timur; post_id=5; comment_id=22
127.0.0.1 - http://127.0.0.1:8080/admin/change_admin/5 - - [2023-04-23 16:16:27,615] - app:admin:185 - INFO - [5; ppzoveda; True] rights was changed by [1; Timur]
127.0.0.1 - http://127.0.0.1:8080/admin/change_admin/5 - - [2023-04-23 16:16:50,126] - app:admin:185 - INFO - User [5; ppzoveda; False] rights was changed by [1; Timur]
127.0.0.1 - http://localhost:8080/api/v2/users/5/token%3DHEAD_TOKEN - - [2023-04-23 16:17:08,549] - app:api_misc:44 - INFO - Token [HEAD_TOKEN] was user
127.0.0.1 - http://localhost:8080/api/v2/users/5/token%3DHEAD_TOKEN - - [2023-04-23 16:17:08,550] - app:users_resource:38 - INFO - 'DELETE' request to [users] resource: user_id=5
127.0.0.1 - http://127.0.0.1:8080/admin/delete_user/5 - - [2023-04-23 16:17:08,559] - app:admin:201 - INFO - [5] was changed by [1; Timur]
127.0.0.1 - http://127.0.0.1:8080/admin/add_token - - [2023-04-23 16:17:59,035] - app:admin:146 - INFO - Token was created by [1; Timur]: token_id=4
127.0.0.1 - http://127.0.0.1:8080/admin/delete_token/4 - - [2023-04-23 16:18:09,823] - app:admin:163 - INFO - Token [4] was deleted by [1; Timur]
127.0.0.1 - http://127.0.0.1:8080/admin/create-post - - [2023-04-23 16:18:24,646] - app:admin:69 - INFO - Post is published by [1; Timur]: 8; t1murCoder_space/8
127.0.0.1 - http://127.0.0.1:8080/admin/create-post - - [2023-04-23 16:19:04,191] - app:app:1744 - ERROR - Exception on /admin/create-post [POST]
Traceback (most recent call last):
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: posts.post_tg_url

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\Timur\Documents\Coding\Python\Lyceum_Tasks\WEB\sites\flask_projects\projects\my_first_flask_project\website\admin.py", line 21, in decorated_view
    return func(*args, **kwargs)
  File "c:\Users\Timur\Documents\Coding\Python\Lyceum_Tasks\WEB\sites\flask_projects\projects\my_first_flask_project\website\admin.py", line 67, in create_post
    db_sess.commit()
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1903, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1218, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1193, in _prepare_impl
    self.session.flush()
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 4155, in flush
    self._flush(objects)
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 4292, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 4252, in _flush
    flush_context.execute()
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 467, in execute
    rec.execute(self)
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 1184, in _emit_insert_statements
    result = connection.execute(
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1414, in execute
    return meth(
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Timur\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: posts.post_tg_url
[SQL: INSERT INTO posts (post_tg_url) VALUES (?)]
[parameters: ('t1murCoder_space/8',)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
127.0.0.1 - http://127.0.0.1:8080/admin/create-post - - [2023-04-23 16:19:38,489] - app:admin:60 - WARNING - Post already exists: t1murCoder_space/8
127.0.0.1 - http://127.0.0.1:8080/admin/create-post - - [2023-04-23 16:20:02,664] - app:admin:60 - WARNING - Post already exists: url=t1murCoder_space/8
127.0.0.1 - http://localhost:8080/api/v2/posts/8/token%3DHEAD_TOKEN - - [2023-04-23 16:20:20,565] - app:api_misc:44 - INFO - Token [HEAD_TOKEN] was used
127.0.0.1 - http://localhost:8080/api/v2/posts/8/token%3DHEAD_TOKEN - - [2023-04-23 16:20:20,568] - app:news_posts_resource:35 - INFO - 'DELETE' request to [news_posts] resource: post_id=8
127.0.0.1 - http://127.0.0.1:8080/admin/delete-post/8 - - [2023-04-23 16:20:20,592] - app:admin:93 - INFO - Post deleted by [1; Timur]: post_id=8;
